"""Interactive setup wizard — generates config.yaml and .env."""

import getpass
import os
import sys
from pathlib import Path

import yaml


_ENV_KEY_MAP = {
    "openai": "OPENAI_API_KEY",
    "anthropic": "ANTHROPIC_API_KEY",
    "gemini": "GEMINI_API_KEY",
}

_PROVIDER_CHOICES = {"1": "openai", "2": "anthropic", "3": "gemini"}


def generate_config(
    bot_name: str,
    domain: str,
    provider: str,
    model: str,
    web_search: bool,
) -> str:
    """Return a YAML string with all config sections."""
    config = {
        "chatbot": {
            "name": bot_name,
            "domain": domain,
        },
        "llm": {
            "provider": provider,
            "model": model,
            "temperature": 0.0,
            "max_tokens": 2048,
        },
        "api_keys": {
            "openai": "",
            "anthropic": "",
            "gemini": "",
        },
        "embeddings": {
            "provider": "local",
            "openai_model": "text-embedding-3-small",
        },
        "retrieval": {
            "chunk_size": 1000,
            "chunk_overlap": 100,
            "top_k": 50,
            "max_distance": 0.55,
        },
        "web_search": {
            "enabled": web_search,
            "backend": "semantic_scholar",
            "max_results": 5,
        },
        "query_understanding": {
            "enabled": True,
            "max_history": 6,
            "max_clarifications": 1,
        },
        "verification": {
            "enabled": True,
            "max_iterations": 3,
            "strict_mode": True,
        },
        "paths": {
            "knowledge_base": "knowledge_base",
            "vector_db": "chroma_db",
        },
    }
    return yaml.dump(config, default_flow_style=False, sort_keys=False)


def generate_env(provider: str, api_key: str) -> str:
    """Return .env file content with the API key for the chosen provider."""
    env_var = _ENV_KEY_MAP.get(provider, f"{provider.upper()}_API_KEY")
    lines = [
        "# Auto-generated by setup wizard",
        f"{env_var}={api_key}",
        "",
    ]
    return "\n".join(lines)


def run_wizard():
    """Five-step interactive setup flow."""
    project_root = Path(__file__).resolve().parent

    print("=" * 50)
    print("  RAG Research Chatbot — Setup Wizard")
    print("=" * 50)
    print()

    # Step 1: Bot name
    bot_name = input("Step 1/5 — Bot name [Research Assistant]: ").strip()
    if not bot_name:
        bot_name = "Research Assistant"

    # Step 2: Domain
    domain = input("Step 2/5 — Domain / topic description: ").strip()
    if not domain:
        domain = "general research"

    # Step 3: Provider
    print("\nStep 3/5 — LLM provider:")
    print("  1) OpenAI")
    print("  2) Anthropic")
    print("  3) Google Gemini")
    provider_choice = input("Choose [1]: ").strip() or "1"
    provider = _PROVIDER_CHOICES.get(provider_choice, "openai")

    # Step 3b: API key
    api_key = getpass.getpass(f"Enter your {provider} API key: ")

    # Step 4: Model selection — fetch available models
    print(f"\nFetching available {provider} models...")
    try:
        from src.llm import list_models
        models = list_models(provider, api_key)
    except Exception:
        # Fallback lists if SDK is not installed or key is invalid
        fallback = {
            "openai": ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano"],
            "anthropic": ["claude-sonnet-4-6", "claude-opus-4-6", "claude-haiku-4-5"],
            "gemini": ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"],
        }
        models = fallback.get(provider, ["default-model"])

    print("\nStep 4/5 — Choose a model:")
    for i, m in enumerate(models, 1):
        print(f"  {i}) {m}")
    model_choice = input(f"Choose [1]: ").strip() or "1"
    try:
        model = models[int(model_choice) - 1]
    except (ValueError, IndexError):
        model = models[0]

    # Step 5: Web search
    print("\nStep 5/5 — Enable web search (Semantic Scholar)?")
    print("  1) Yes")
    print("  2) No")
    ws_choice = input("Choose [1]: ").strip() or "1"
    web_search = ws_choice == "1"

    # Write config.yaml
    config_path = project_root / "config.yaml"
    config_str = generate_config(bot_name, domain, provider, model, web_search)
    config_path.write_text(config_str)
    print(f"\n  Wrote {config_path}")

    # Write .env
    env_path = project_root / ".env"
    env_str = generate_env(provider, api_key)
    env_path.write_text(env_str)
    print(f"  Wrote {env_path}")

    # Create knowledge_base/ directory
    kb_dir = project_root / "knowledge_base"
    kb_dir.mkdir(exist_ok=True)
    print(f"  Created {kb_dir}/")

    # Next steps
    print("\n" + "=" * 50)
    print("  Setup complete! Next steps:")
    print("=" * 50)
    print(f"  1. Add documents to {kb_dir}/")
    print("  2. Run: python ingest.py")
    print("  3. Run: python app_cli.py  (or: streamlit run app_web.py)")
    print()


if __name__ == "__main__":
    run_wizard()
