"""SQL retriever: execute validated queries against the SQLite knowledge base."""

import os
import sqlite3
from pathlib import Path


def _validate_sql(sql: str) -> bool:
    """Validate that a SQL string is a safe SELECT query.

    Rejects non-SELECT statements and queries containing semicolons
    (which could chain dangerous statements).
    """
    stripped = sql.strip()
    if not stripped:
        return False
    if ";" in stripped:
        return False
    if not stripped.upper().startswith("SELECT"):
        return False
    return True


def _get_db_path(cfg: dict) -> str:
    """Resolve the SQLite database path from config."""
    sql_db_dir = cfg.get("paths", {}).get("sql_db", "sql_db")
    if not os.path.isabs(sql_db_dir):
        project_root = Path(__file__).resolve().parent.parent
        sql_db_dir = os.path.join(str(project_root), sql_db_dir)
    return os.path.join(sql_db_dir, "knowledge_base.db")


def execute_sql_query(sql_query: str, cfg: dict) -> list[dict]:
    """Execute a validated SELECT query against the knowledge base SQLite DB.

    Args:
        sql_query: A SQL SELECT query (generated by the LLM).
        cfg: App config dict.

    Returns:
        List of row dicts, or empty list on any error.
    """
    if not _validate_sql(sql_query):
        return []

    db_path = _get_db_path(cfg)
    if not os.path.exists(db_path):
        return []

    max_rows = cfg.get("sql", {}).get("max_rows", 200)

    try:
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        try:
            conn.row_factory = sqlite3.Row
            cursor = conn.execute(sql_query)
            rows = cursor.fetchmany(max_rows)
            return [dict(row) for row in rows]
        finally:
            conn.close()
    except Exception:
        return []


def format_sql_results_as_context(
    rows: list[dict], sql_query: str, source_file: str,
    table_info: dict = None,
) -> str:
    """Format SQL result rows as context for the verification pipeline.

    Uses [CHUNK-SQL-NNN] IDs for internal anchoring, consistent with
    CHUNK-LOCAL and CHUNK-WEB patterns.

    Args:
        rows: Query result rows as dicts.
        sql_query: The SQL query that produced these rows.
        source_file: Original source file path.
        table_info: Schema entry for the table (includes column descriptions).
    """
    if not rows:
        return ""

    parts = [
        "=== SQL Query Results (PRIMARY — from local dataset) ===\n",
        f"Query: {sql_query}",
        f"Source: {source_file}",
        f"Rows returned: {len(rows)}\n",
    ]

    # Include table and column descriptions so the LLM understands the data
    if table_info:
        table_desc = table_info.get("table_description", "")
        if table_desc:
            parts.append(f"Dataset description: {table_desc}\n")
        col_descs = {
            c["name"]: c.get("description", "")
            for c in table_info.get("columns", [])
        }
        desc_lines = [f"  {name}: {desc}" for name, desc in col_descs.items() if desc]
        if desc_lines:
            parts.append("Column descriptions:")
            parts.extend(desc_lines)
            parts.append("")

    for i, row in enumerate(rows, 1):
        fields = ", ".join(
            f"{k} = {v if v is not None else 'N/A'}" for k, v in row.items()
        )
        parts.append(f"[CHUNK-SQL-{i:03d}] {fields}")
    return "\n".join(parts)


def _lookup_source_file(table_name: str, schema: dict) -> str:
    """Look up the original source file for a SQL table name."""
    entry = schema.get(table_name)
    if entry:
        return entry.get("source_file", table_name)
    return table_name


def build_schema_summary(schema: dict) -> str:
    """Build a compact schema summary for injection into the QU prompt.

    Includes column descriptions (from codebook or LLM inference),
    sample values, and statistics so the LLM knows what data looks like
    for correct WHERE clauses and aggregation queries.
    """
    if not schema:
        return ""

    lines = ["Available SQL tables:"]
    for table_name, info in schema.items():
        row_count = info.get("row_count", 0)
        source = info.get("source_file", "")
        table_desc = info.get("table_description", "")

        header = f"\n- {table_name} ({row_count} rows, from {source}):"
        if table_desc:
            header += f"\n  Description: {table_desc}"
        lines.append(header)

        for c in info.get("columns", []):
            col_type = c.get("type", "TEXT")
            stats = c.get("stats", {})
            samples = c.get("sample", [])
            desc = c.get("description", "")

            # Build metadata string
            meta_parts = [col_type]
            unique_count = stats.get("unique_count")
            col_min = stats.get("min")
            col_max = stats.get("max")

            if col_min is not None and col_max is not None:
                meta_parts.append(f"range {col_min}\u2013{col_max}")
            if unique_count is not None:
                meta_parts.append(f"{unique_count} unique")

            meta_str = ", ".join(meta_parts)

            # Build sample string
            sample_str = ""
            if samples:
                quoted = ", ".join(f'"{s}"' for s in samples[:5])
                sample_str = f" e.g. {quoted}"

            col_name = c.get("name", "unknown")
            line = f"    {col_name} ({meta_str}){sample_str}"
            if desc:
                line += f" \u2014 {desc}"
            lines.append(line)
    return "\n".join(lines)
