"""SQL retriever: execute validated queries against the SQLite knowledge base."""

import os
import sqlite3
from pathlib import Path


def _validate_sql(sql: str) -> bool:
    """Validate that a SQL string is a safe SELECT query.

    Rejects non-SELECT statements and queries containing semicolons
    (which could chain dangerous statements).
    """
    stripped = sql.strip()
    if not stripped:
        return False
    if ";" in stripped:
        return False
    if not stripped.upper().startswith("SELECT"):
        return False
    return True


def _get_db_path(cfg: dict) -> str:
    """Resolve the SQLite database path from config."""
    sql_db_dir = cfg.get("paths", {}).get("sql_db", "sql_db")
    if not os.path.isabs(sql_db_dir):
        project_root = Path(__file__).resolve().parent.parent
        sql_db_dir = os.path.join(str(project_root), sql_db_dir)
    return os.path.join(sql_db_dir, "knowledge_base.db")


def execute_sql_query(sql_query: str, cfg: dict) -> list[dict]:
    """Execute a validated SELECT query against the knowledge base SQLite DB.

    Args:
        sql_query: A SQL SELECT query (generated by the LLM).
        cfg: App config dict.

    Returns:
        List of row dicts, or empty list on any error.
    """
    if not _validate_sql(sql_query):
        return []

    db_path = _get_db_path(cfg)
    if not os.path.exists(db_path):
        return []

    max_rows = cfg.get("sql", {}).get("max_rows", 200)

    try:
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        conn.row_factory = sqlite3.Row
        cursor = conn.execute(sql_query)
        rows = cursor.fetchmany(max_rows)
        result = [dict(row) for row in rows]
        conn.close()
        return result
    except Exception:
        return []
